### ISSUE TITLE
[Feature request] Sort Properties

### ISSUE THREAD

**Issue by marcusmoore** [anyboxhq/everything-okjson#11]
**Is your feature request related to a problem? Please describe.**
This isn't a problem but I would love to have the ability to sort the JSON that I paste into the app. I never find myself concerned with the order of the properties but often scan the properties for a specific key.

**Describe the solution you'd like**
Personally, if there was a preference to "always sort properties when pasting" I would be very happy but another, and potentially more popular with most users, is a keyboard shortcut to sort after pasting.

Another option might be a keyboard shortcut/text box similar to "Find" that can "Filter" properties.

**Describe alternatives you've considered**
`CMD+F` for find is helpful for general searches since it will also search the contents of the values but for my use-case, easily scanning the properties for a specific key, it would be easier if they were sorted alphabetically.

Thanks for your consideration and for the great app 😄

**Comment by francisfeng** [comment]
It’s supported in 2.0.
