### ISSUE TITLE
Pasting new content into already named tab, resets the tab name

### ISSUE THREAD

**Issue by shames0** [anyboxhq/everything-okjson#18]
**Describe the bug**
When pasting new JSON content into an already named OK JSON window, the previously given name is removed, and is replaced with "Today at {TIME}"
(this may be related to #17)

**To Reproduce**
1. Open the OK JSON app
2. Click the "Rename tab" button to name the initial tab (e.g. "My First Tab")
3. Paste JSON content into the window
4. Note that the Tab name changed from "My First Tab" to "Today at {TIME}"

This occurs on any open tab, whether you have one tab open, or many. When you paste new content, the name is changed from what you named it to.

**Expected behavior**
The tab name that was given to the tab by the user should be preserved

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1 (22D68)
 - Browser: N/A - using the OK JSON macOS app
 - Version 1.9.0 (26)

**Comment by francisfeng** [comment]
It’s fixed in 2.0.
