### ISSUE TITLE
Persist JSON data when app is quit and reload JSONs which were open from previous session when app relaunched

### ISSUE THREAD

**Issue by pavan6e** [anyboxhq/everything-okjson#21]
**Is your feature request related to a problem? Please describe.**
I had to quit the app due to some unexpected reasons and i generally work with multiple json tabs and reopening all tabs is a tedious task

**Describe the solution you'd like**
App should prompt users to whether save the opened JSON tabs or not. When app is re-launched, the persisted JSONs tabs should recover

**Describe alternatives you've considered**
tedious but able to manage it. I have saved all json data in a location temporarily managing it. I purchased the app expecting this feature but this feature is missing.

**Comment by francisfeng** [comment]
It’s supported in 2.0.
