### ISSUE TITLE
Feature request: Single left click to follow hyperlink

### ISSUE THREAD

**Issue by vincentardern** [anyboxhq/everything-okjson#22]
Hi,

The app (or is it macOS) clearly understands what a URL is, as it can be followed when right clicking on the link.

Could you please make it so that single left clicking on the link can follow it? Perhaps with an option to enable / disable this behaviour. With an underline in the formatting would be even nicer.

Thanks

**Comment by francisfeng** [comment]
Then it will be conflicted with selection action. I’m very careful about adding new options at the moment.

**However, you can double-click to open the link**. And adding underline seems like a good idea. But I will have to see how it looks.
