### ISSUE TITLE
Be able to read `jsonl` format, 支持 `jsonl` 格式的文件

### ISSUE THREAD

**Issue by simonrouse9461** [anyboxhq/everything-okjson#25]
**Is your feature request related to a problem? Please describe.**
OK JSON is not able to open [jsonlines](https://jsonlines.org) files with `.jsonl` extension.

**Describe the solution you'd like**
Read `jsonl` files as a list of objects.

**Describe alternatives you've considered**
No alternatives

**Additional context**
N/A

**Comment by francisfeng** [comment]
Suppoorted in version 2.4.
