### ISSUE TITLE
Not OK Json! The Editor Fails to display any text!

### ISSUE THREAD

**Issue by MarqueIV** [anyboxhq/everything-okjson#29]
This image explains it all.

![image](https://github.com/anyboxhq/everything-okjson/assets/897883/24d1e92f-efb9-45da-8d83-f4bdf3b2ee90)

![image](https://github.com/anyboxhq/everything-okjson/assets/897883/eca6f8d6-fc39-4d7c-939e-e0f292cf3e74)

The rest I'm copying from my review on the app store which I just left so I don't have to re-type it.

--Original Review - 2/5 Stars--

This had the potential to be a perfect, simple JSON editor.  Easily one of the best-looking ones I've seen to date.  But usability issues knock it off-course, and the incomprehensible fact that it fails to display actual JSON doesn't just make this version trip out of the gate, it makes it flat-out DOA. How the heck did this get through QA?!

Ok, the details...

The first, and by far the biggest... it fails to display the actual JSON in the editor. It simply doesn't work!  Specifically, when you open a JSON file in the latest version, you can see the tree on the left, filled in as expected, but there is no raw text JSON on the right.  You can see the line numbers so it did try to load something, but there's nothing after them.  I even wondered if maybe it was a misconfigured font color (i.e. white font on a white background) where selecting it would reveal the 'hidden' text, but nope... there was simply nothing there!

I even thought 'Ok... maybe it's the app-store version. Surely they have a newer version on their own web site!' so I deleted the app store one, went to their site and grabbed that one.

Same broken issue. Such a shame.

Even if that weren't the case, other things that keep this from a perfect app...

One. There doesn't seem to be a way to simply create a new, blank JSON document that you can type in yourself!  Yes, you heard that right... there's no 'File-New!' in a JSON editor! What!?!! You can only start from the pasteboard, a URL, a cURL response or by opening an existing file.  Sure, there's a 'new' button on the toolbar, but it's not for creating a new document. Because of that, it should not be the 'new document' icon. It should be a new *viewer* icon. But again, sometimes I want to *create* a file and I shouldn't have to go somewhere else to create it first.  Really... how is such a basic feature missing?

Two. Why is there a separate 'Viewer' mode vs non-viewer mode?  There should only be one mode... view/edit.  It should handle read-only files of course, and perhaps you may want to toggle editing/lock the view so you don't accidentally change something, but what if you do want to and you're in the 'viewer' mode?  You have to copy/paste it to a completely different viewer... sorry... editor... meaning you most likely will also completely lose where you were in that file! Again, why?!

Three. The 'Zoom In Node' is brilliant!  Or rather should have been. It too falters. 'Zoom in node' is when you basically 're-anchor' the 'tree view' to a specific child node so you're only seeing that node as the root. This lets you focus on only what you're interested in at that moment.  Or rather apparently permanently because the only way to go back out is to CTRL-Z! That's 'undo'!  What exactly are you undoing?! Undo is for when you change something but nothing about the document changed, only how it's being viewed!

...or so I thought.  What appears to be happening is the developer is literally discarding everything else and creating a new JSON document of just that node.

But why?

Again, you have the document, you know where you are in the tree because you already know how to render the breadcrumb down below.  Why not allow us to navigate back up the tree, like any other navigating with the breadcrumb? Maybe even 'gray out' the portions 'above' the root as a visual indicator of where you're rooted, but still allow us to click back out of it.  But nope... it's a one-way trip unless you immediately CTRL-Z to get back out of it.  Like I said, missed opportunity here.

So again, this could have been a perfect JSON viewer.  It's gorgeously rendered, seems very performant, and is dead-simple.  Add in the scripting support and it should've been game-over.  But the above usability issues keep this from being five-star, and the downright broken editor keeps it from being usable at all.   And at $20 after two weeks, Apple customers really deserve better.

Hopefully, the developer is listening, and if so and these get addressed, I'll happily adjust my review, possibly up to the hoped-for five-stars I thought it was when I first found it.  But for now, I'm only saying two, not one, because they clearly care about the appearance which is more than most can say.  But it just doesn't work!  So close, yet so, so far.

**Comment by francisfeng** [comment]
Ranting and giving low rating is not going to help with your problem.

If you want your problem solved, be polite.
