### ISSUE TITLE
设置页面，导航 tab 页里面，字体设置项，字体大小无法调节，永远 13 号

### ISSUE THREAD

**Issue by yubobo** [anyboxhq/everything-okjson#32]
设置页面，导航 tab 页里面，字体设置项，字体大小无法调节，永远 13 号

<img width="589" alt="image" src="https://github.com/anyboxhq/everything-okjson/assets/4443390/b671a20e-6311-494e-a63a-1fc3655e0146">

版本：
<img width="318" alt="image" src="https://github.com/anyboxhq/everything-okjson/assets/4443390/d14bafae-b94c-4e53-acbe-c658a4b3baf3">

@francisfeng

**Comment by francisfeng** [comment]
请通过⌘ = / - 或菜单项「显示 → 放大/缩小」来调整导航的字体大小。
