### ISSUE TITLE
Add list-index number to string/integer lists

### ISSUE THREAD

**Issue by joshorr** [anyboxhq/everything-okjson#33]
**Is your feature request related to a problem? Please describe.**

The list-index is present if the value is an object or another list (ie: something you can 'expand').  The list-index is absent if the value is a basic string/integer.

I'm dealing with json sub-lists with hundreds of basic strings and integers.  It's difficult to figure out what index something is at. 

My current workaround is to use the line-number listing on the right-pane after clicking on the full list, and subtract 2 (due to starting at '1' and the first line number on the right being the `[` char).  So that's my current work around, but it would be really nice if I could just see a direct index on the left-side/pane on basic string and integer lists.

**Describe the solution you'd like**

Regardless of the value type in a list, I would like to see the values index in the list it's in; similar to how lists of objects have their index listed next to their value.

**Comment by francisfeng** [comment]
Are you suggesting something like this in the screenshot?

![OK JSON](https://github.com/user-attachments/assets/7d09f011-bf9e-43bb-8fe2-f7baa6e6d955)

**Comment by joshorr** [comment]
Perfect!

**Comment by joshorr** [comment]
(It would be awesome if the same indexing was available for lists of integers too, but going this far is most helpful!)

**Comment by francisfeng** [comment]
It looks like a nice addition. So I implemented this feature. Will be available in the next version.

![primitive type index](https://github.com/user-attachments/assets/14a255e4-4791-4959-81fe-ee611b10d35f)

**Comment by joshorr** [comment]
Thank you so much!  I deal with lists with hundreds of strings where they are referenced by their index.

this will help a lot!
