### ISSUE TITLE
JSON Lines support?

### ISSUE THREAD

**Issue by aurrak** [anyboxhq/everything-okjson#37]
**Describe the bug**
I am not able to open a .jsonl file or opening json lines from pasteboard.

**To Reproduce**
1. Try to open any .jsonl file.
2. Open dialog does not allow opening file with .json file extension
3. Try to open json lines using the "New from Pasteboard" option
4. Got an error saying `No valid JSON string is found in pasteboard`

**Expected behavior**
Able to open jsonl file or content

**Screenshots**
<img width="256" alt="image" src="https://github.com/user-attachments/assets/c326e0f8-fb4d-4532-8637-a3d83b302eb7">

<img width="656" alt="image" src="https://github.com/user-attachments/assets/16f4d880-75af-4d28-8b42-695898eed58e">

**Comment by francisfeng** [comment]
Opening `jsonl` files will be supported in the next version.
